import 'dart:ui';
import 'package:flutter/material.dart';
import '../../core/app_export.dart';

/// Helper class for managing themes and colors.
class ThemeHelper {
  // The current app theme
  var _appTheme = PrefUtils().getThemeData();

// A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Changes the app theme to [_newTheme].
  void changeTheme(String _newTheme) {
    PrefUtils().setThemeData(_newTheme);
    Get.forceAppUpdate();
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: appTheme.blue700,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(
              28,
            ),
          ),
          shadowColor: colorScheme.primary,
          elevation: 4,
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        bodyLarge: TextStyle(
          color: colorScheme.primary.withOpacity(1),
          fontSize: getFontSize(
            16,
          ),
          fontFamily: 'Roboto',
          fontWeight: FontWeight.w400,
        ),
        bodyMedium: TextStyle(
          color: colorScheme.primary.withOpacity(1),
          fontSize: getFontSize(
            14,
          ),
          fontFamily: 'Roboto',
          fontWeight: FontWeight.w400,
        ),
        bodySmall: TextStyle(
          color: colorScheme.primary.withOpacity(1),
          fontSize: getFontSize(
            11,
          ),
          fontFamily: 'Roboto',
          fontWeight: FontWeight.w300,
        ),
        displayMedium: TextStyle(
          color: colorScheme.primary.withOpacity(1),
          fontSize: getFontSize(
            40,
          ),
          fontFamily: 'Roboto',
          fontWeight: FontWeight.w700,
        ),
        displaySmall: TextStyle(
          color: appTheme.whiteA700,
          fontSize: getFontSize(
            36,
          ),
          fontFamily: 'Inter',
          fontWeight: FontWeight.w400,
        ),
        headlineSmall: TextStyle(
          color: colorScheme.primary.withOpacity(1),
          fontSize: getFontSize(
            24,
          ),
          fontFamily: 'Roboto',
          fontWeight: FontWeight.w400,
        ),
        titleLarge: TextStyle(
          color: appTheme.whiteA700,
          fontSize: getFontSize(
            20,
          ),
          fontFamily: 'Roboto',
          fontWeight: FontWeight.w700,
        ),
        titleMedium: TextStyle(
          color: colorScheme.primaryContainer,
          fontSize: getFontSize(
            16,
          ),
          fontFamily: 'Roboto',
          fontWeight: FontWeight.w700,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0X3F000000),
    primaryContainer: Color(0XFF2300FF),
    secondary: Color(0XFF2300FF),
    secondaryContainer: Color(0X3F000000),
    tertiary: Color(0XFF2300FF),
    tertiaryContainer: Color(0X3F000000),

    // Background colors
    background: Color(0XFF2300FF),

    // Surface colors
    surface: Color(0XFF2300FF),
    surfaceTint: Color(0XFFBB0303),
    surfaceVariant: Color(0X3F000000),

    // Error colors
    error: Color(0XFFBB0303),
    errorContainer: Color(0XFFB99FD9),
    onError: Color(0XFFDFE9F3),
    onErrorContainer: Color(0XFF2300FF),

    // On colors(text colors)
    onBackground: Color(0XFFB99FD9),
    onInverseSurface: Color(0XFFDFE9F3),
    onPrimary: Color(0XFFBB0303),
    onPrimaryContainer: Color(0XFFB99FD9),
    onSecondary: Color(0XFFB99FD9),
    onSecondaryContainer: Color(0XFFBB0303),
    onTertiary: Color(0XFFB99FD9),
    onTertiaryContainer: Color(0XFFBB0303),

    // Other colors
    outline: Color(0XFFBB0303),
    outlineVariant: Color(0XFF2300FF),
    scrim: Color(0XFF2300FF),
    shadow: Color(0XFFBB0303),

    // Inverse colors
    inversePrimary: Color(0XFF2300FF),
    inverseSurface: Color(0XFFBB0303),

    // Pending colors
    onSurface: Color(0XFFB99FD9),
    onSurfaceVariant: Color(0XFFBB0303),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Blue
  Color get blue700 => Color(0XFF2376C2);
  Color get blue70001 => Color(0XFF1A7ED9);

  // BlueGray
  Color get blueGray100 => Color(0XFFD9D9D9);
  Color get blueGray400 => Color(0XFF908888);
  Color get blueGray40001 => Color(0XFF888888);

  // DeepPurple
  Color get deepPurple200 => Color(0XFFB99FD9);

  // Gray
  Color get gray400 => Color(0XFFBCBCBC);
  Color get gray700 => Color(0XFF595959);

  // Green
  Color get greenA700 => Color(0XFF05FF00);

  // Indigo
  Color get indigo400 => Color(0XFF6568B4);
  Color get indigoA700 => Color(0XFF021BFF);
  Color get indigoA70002 => Color(0XFF433FFF);

  // LightGreen
  Color get lightGreenA400 => Color(0XFF51FF00);

  // Lime
  Color get limeA400 => Color(0XFFBCFF00);

  // Orange
  Color get orange700 => Color(0XFF000000);

  // Red
  Color get redA700 => Color(0XFFFF0000);

  // Teal
  Color get teal50 => Color(0XFFDFE9F3);

  // White
  Color get whiteA700 => Color(0XFFFFFFFF);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
